#!/usr/bin/env python2.7
import sys
import os
import os.path
import pprint
import cStringIO
import socket
import struct

def aton_ip(ip):
    return bytearray(socket.inet_aton(ip))

def aton_mac(mac):
    return struct.pack('6B', *(int(x,base=16) for x in mac.split(':')))

def aton_tunid(tid):
    return struct.pack('<H', tid)

def set_val(field, val):
    output = field.copy()
    output.update({'value' : val})
    return output


HWSRC  ={'offset' :  0,
         'size'   :  6}
HWDST  ={'offset' :  6,
         'size'   :  6}
ETHTYPE={'offset' : 12,
         'size'   :  2}
VLANID ={'offset' : 14,
         'size'   :  2}
IPSRC  ={'offset' : 26,
         'size'   :  4}
IPDST  ={'offset' : 30,
         'size'   :  4}

INPORT ={'name'   : 'in_port',
         'size'   :  1}
TUNID  ={'name'   : 'tun_id',
         'size'   :  2}
TUNDST ={'name'   : 'tun_dst',
         'size'   :  4} 

TYPE_QINQ=0x88A8
TYPE_VLAN=0x8100


LIBBESS='~/bess/libbess-python'

try:
    this_dir = os.path.expanduser(LIBBESS)
    sys.path.insert(1, this_dir)
    from bess import *
except ImportError:
    print >> sys.stderr, 'Cannot import the API module (libbess-python)'

    
def connect_bess():
    B = BESS()
    try:
        B.connect()
    except B.APIError as e:
        print >> sys.stderr, e.message
    return B

if __name__ == '__main__':
    B = connect_bess()
    if B.is_connected():
        print '%s:%d' % B.peer
    else:
        print '<disconnected>'

    B.pause_all()
    B.reset_all()
    B.resume_all()


    #### CREATE MODULES ####
    name='OUT'
    for i in range(1,5):
        B.create_module('Sink', name=name + str(i), arg=None)
    name='DRP'
    for i in range(1,6):
        B.create_module('Sink', name=name + str(i), arg=None)
    B.create_module('Sink', name='LCL', arg=None)
    B.create_module('Sink', name='CTL', arg=None)
    
    B.create_module('WildcardMatch',
                    name='t0_start',
                    arg={'fields' : [ETHTYPE,VLANID],
                         'size' : 4096})
    B.create_module('ExactMatch',
                    name='t0_inport',
                    arg={'fields' : [INPORT],
                         'size' : 4096})
    B.create_module('BPF', name='t0_p2')
    B.create_module('BPF', name='t0_default')


    B.create_module('WildcardMatch',
                    name='t1_start',
                    arg={'fields' : [INPORT,IPSRC],
                         'size' : 4096})

    
    B.create_module('WildcardMatch',
                    name='t2_start',
                    arg={'fields' : [IPSRC,IPDST],
                         'size' : 4096})

    

    B.create_module('ExactMatch',
                    name='t3_start',
                    arg={'fields' : [INPORT],
                         'size' : 4096})

    
    B.create_module('ExactMatch',
                    name='t4_start',
                    arg={'fields' : [IPDST],
                         'size' : 4096})
    B.create_module('Update',
                    name='t4u1',
                    arg=[set_val(HWDST,'fa:16:3e:cf:f2:56')])
    B.create_module('Update',
                    name='t4u2',
                    arg=[set_val(HWDST,'fa:16:3e:f3:5e:82'),
                         set_val(TUNID, 0x40c),
                         set_val(TUNDST,'1.1.1.2')])
    B.create_module('Update',
                    name='t4u3',
                    arg=[set_val(HWDST,'fa:16:3e:da:05:ed'),
                         set_val(TUNID, 0x406),
                         set_val(TUNDST, '1.1.1.2')])
    B.create_module('Update',
                    name='t4u4',
                    arg=[set_val(HWDST, 'fa:16:3e:3e:82:e8')])
    

    B.create_module('ExactMatch',
                    name='t5_start',
                    arg={'fields' : [TUNID,HWSRC],
                         'size' : 4096})

    
    B.create_module('BPF', name='t6_start')
    B.create_module('VLANPop', name='vlan_pop')


    B.create_module('HashLB',
                    name='grp_start',
                    arg=2)

    
    #### CONNECT MODULES ####
    B.pause_all()
    try:
        B.connect_modules('t0_start', 't6_start'   , 1, 0)
        B.connect_modules('t0_start', 't0_inport'  , 0, 0)
        
        B.connect_modules('t0_inport', 't0_p2'     , 1, 0)
        B.connect_modules('t0_inport', 'OUT2'      , 2, 0)
        B.connect_modules('t0_inport', 't0_default', 0, 0)
        
        B.connect_modules('t0_p2', 'LCL'           , 1, 0)
        B.connect_modules('t0_p2', 't0_default'    , 0, 0)
        
        B.connect_modules('t0_default', 'CTL'      , 1, 0)
        B.connect_modules('t0_default', 't1_start' , 0, 0)

        B.connect_modules('t1_start'  , 't5_start' , 0, 0)
        B.connect_modules('t1_start'  , 't4_start' , 1, 0)
        B.connect_modules('t1_start'  , 't2_start' , 2, 0)
        B.connect_modules('t1_start'  , 't3_start' , 3, 0)
        B.connect_modules('t1_start'  , 'DRP1'     , 4, 0)

        B.connect_modules('t2_start'  , 'grp_start', 1, 0)
        B.connect_modules('t2_start'  , 't4_start' , 2, 0)
        B.connect_modules('t2_start'  , 'DRP2'     , 3, 0)
        B.connect_modules('t2_start'  , 'OUT2'     , 0, 0)

        B.connect_modules('t3_start'  , 'grp_start', 1, 0)
        B.connect_modules('t3_start'  , 'DRP3'     , 0, 0)

        B.connect_modules('t4_start'  , 't4u1'     , 1, 0)
        B.connect_modules('t4u1'      , 'OUT4'     , 0, 0)
        B.connect_modules('t4_start'  , 't4u2'     , 2, 0)
        B.connect_modules('t4u2'      , 'OUT1'     , 0, 0)
        B.connect_modules('t4_start'  , 't4u3'     , 3, 0)
        B.connect_modules('t4u3'      , 'OUT1'     , 0, 0)
        B.connect_modules('t4_start'  , 't4u4'     , 4, 0)
        B.connect_modules('t4u4'      , 'OUT3'     , 0, 0)

        B.connect_modules('t5_start'  , 'OUT3'     , 1, 0)
        B.connect_modules('t5_start'  , 'OUT4'     , 2, 0)
        B.connect_modules('t5_start'  , 'DRP4'     , 0, 0)

        B.connect_modules('t6_start'  , 'CTL'      , 1, 0)
        B.connect_modules('t6_start'  , 'vlan_pop' , 2, 0)
        B.connect_modules('vlan_pop'  , 'OUT2'     , 0, 0)
        B.connect_modules('t6_start'  , 'DRP5'     , 0, 0)
        
    finally:
        B.resume_all()    



    #### ADD RULES TO MODULES ####
        
    #table=0 priority=55000 vlan_tci=0x1000/0x1000 actions=goto_table:6
    B.run_module_command('t0_start','add', {'priority' : 55000,
                                            'values'   : [TYPE_VLAN, 0x1000],
                                            'masks'    : [0xffff,    0x1000],
                                            'gate'     : 1 })
    B.run_module_command('t0_start','add', {'priority' : 55000,
                                            'values'   : [TYPE_QINQ, 0x1000],
                                            'masks'    : [0xffff,    0x1000],
                                            'gate'     : 1 })

    # port 2 to t0_p2
    B.run_module_command('t0_inport','add', {'fields'  : [bytearray(chr(2))],
                                             'gate'    : 1})
    #table=0 priority=50000	in_port=LOCAL actions=output:2
    B.run_module_command('t0_inport','add', {'fields'  : [bytearray(chr(101))],
                                             'gate'    : 2})
    
    # table=0 priority=50000 ip in_port=2 nw_dst=1.1.1.1 actions=LOCAL
    B.run_module_command('t0_p2','add', [{'priority' : 50000,
                                          'filter'   : 'ip and dst host 1.1.1.1',
                                          'gate'     : 1 }])
    #table=0 priority=50000	arp in_port=2 arp_tpa=1.1.1.1 actions=LOCAL
    B.run_module_command('t0_p2','add', [{'priority' : 50000,
                                          'filter'   : 'arp and dst host 1.1.1.1',
                                          'gate'     : 1 }])
    #table=0 priority=50000	udp in_port=2 tp_dst=4789 actions=LOCAL
    B.run_module_command('t0_p2','add', [{'priority' : 50000,
                                          'filter'   : 'udp and dst port 4789',
                                          'gate'     : 1 }])
    
    # table=0 priority=40000 udp tp_src=68 tp_dst=67 actions=CONTROLLER:65535
    B.run_module_command('t0_default','add', [{'priority' : 40000,
                                               'filter'   : 'udp and src port 68 and dst port 67',
                                               'gate'     : 1 }])
    # table=0 priority=40000 dl_type=0x88cc	actions=CONTROLLER:65535
    B.run_module_command('t0_default','add', [{'priority' : 40000,
                                               'filter'   : 'ether proto 0x88cc',
                                               'gate'     : 1 }])
    # table=0 priority=0 actions=goto_table:1
    B.run_module_command('t0_default','add', [{'priority' : 40000,
                                               'filter'   : 'ether proto 0x8942',
                                               'gate'     : 1 }])
    #table=0 priority=40000	arp actions=CONTROLLER:65535
    B.run_module_command('t0_default','add', [{'priority' : 40000,
                                               'filter'   : 'arp',
                                               'gate'     : 1 }])


    # table=1 priority=5000 in_port=1                      actions=goto_table:5
    B.run_module_command('t1_start','add', {'priority' : 5000,
                                            'values'   : [1,    aton_ip('0.0.0.0')],
                                            'masks'    : [0xff, aton_ip('0.0.0.0')],
                                            'gate'     : 0 })

    # table=1 priority=5000 in_port=2                      actions=goto_table:4
    B.run_module_command('t1_start','add', {'priority' : 5000,
                                            'values'   : [2,    aton_ip('0.0.0.0')],
                                            'masks'    : [0xff, aton_ip('0.0.0.0')],
                                            'gate'     : 1 })
    # table=1 priority=5000 ip in_port=3 nw_src=10.10.10.3 actions=goto_table:2
    B.run_module_command('t1_start','add', {'priority' : 5000,
                                            'values'   : [3,    aton_ip('10.10.10.3')], 
                                            'masks'    : [0xff, aton_ip('255.255.255.255')], 
                                            'gate'     : 2 })
    # table=1 priority=5000 ip in_port=4 nw_src=10.10.12.3 actions=goto_table:2
    B.run_module_command('t1_start','add', {'priority' : 5000,
                                            'values'   : [4,    aton_ip('10.10.12.3')], 
                                            'masks'    : [0xff, aton_ip('255.255.255.255')], 
                                            'gate'     : 2 })
    # table=1 priority=4000 in_port=3                      actions=goto_table:3
    B.run_module_command('t1_start','add', {'priority' : 4000,
                                            'values'   : [3,    aton_ip('0.0.0.0')], 
                                            'masks'    : [0xff, aton_ip('0.0.0.0')], 
                                            'gate'     : 3 })
    # table=1 priority=4000 in_port=4                      actions=goto_table:3
    B.run_module_command('t1_start','add', {'priority' : 4000,
                                            'values'   : [3,    aton_ip('0.0.0.0')], 
                                            'masks'    : [0xff, aton_ip('0.0.0.0')], 
                                            'gate'     : 3 })
    # otherwise drop
    B.run_module_command('t1_start','set_default_gate', 4)

    
    # table=2 priority=50000 ip nw_src=10.10.10.0/24 nw_dst=10.10.12.1 actions=group:2953848289
    B.run_module_command('t2_start','add', {'priority' : 50000,
                                            'values'   : [aton_ip('10.10.10.0'),    aton_ip('10.10.12.1')], 
                                            'masks'    : [aton_ip('255.255.255.0'), aton_ip('255.255.255.255')], 
                                            'gate'     : 1})
    # table=2 priority=5000 ip nw_src=10.10.12.0/24 nw_dst=10.10.12.0/24 actions=goto_table:4
    B.run_module_command('t2_start','add', {'priority' : 5000,
                                            'values'   : [aton_ip('10.10.12.0'),    aton_ip('10.10.12.0')], 
                                            'masks'    : [aton_ip('255.255.255.0'), aton_ip('255.255.255.0')],
                                            'gate'     : 2})
    # table=2 priority=5000 ip nw_src=10.10.12.0/24 nw_dst=10.10.10.0/24 actions=goto_table:4
    B.run_module_command('t2_start','add', {'priority' : 5000,
                                            'values'   : [aton_ip('10.10.12.0'),    aton_ip('10.10.10.0')], 
                                            'masks'    : [aton_ip('255.255.255.0'), aton_ip('255.255.255.0')],
                                            'gate'     : 2})
    # table=2 priority=5000 ip nw_src=10.10.10.0/24 nw_dst=10.10.12.0/24 actions=goto_table:4
    B.run_module_command('t2_start','add', {'priority' : 5000,
                                            'values'   : [aton_ip('10.10.10.0'),    aton_ip('10.10.12.0')], 
                                            'masks'    : [aton_ip('255.255.255.0'), aton_ip('255.255.255.0')],
                                            'gate'     :  2})
    # table=2 priority=5000 ip nw_src=10.10.10.0/24 nw_dst=10.10.10.0/24 actions=goto_table:4
    B.run_module_command('t2_start','add', {'priority' : 5000,
                                            'values'   : [aton_ip('10.10.10.0'),    aton_ip('10.10.10.0')], 
                                            'masks'    : [aton_ip('255.255.255.0'), aton_ip('255.255.255.0')],
                                            'gate'     : 2})
    # table=2 priority=4000 ip nw_dst=10.10.10.0/24 actions=drop
    B.run_module_command('t2_start','add', {'priority' : 4000,
                                            'values'   : [aton_ip('0.0.0.0'),    aton_ip('10.10.10.0')], 
                                            'masks'    : [aton_ip('0.0.0.0'), aton_ip('255.255.255.0')],
                                            'gate'     : 3})
    # table=2 priority=4000 ip nw_dst=10.10.12.0/24 actions=drop
    B.run_module_command('t2_start','add', {'priority' : 4000,
                                            'values'   : [aton_ip('0.0.0.0'),    aton_ip('10.10.12.0')], 
                                            'masks'    : [aton_ip('0.0.0.0'), aton_ip('255.255.255.0')],
                                            'gate'     : 3})
    # table=2 priority=0 actions=output:2
    B.run_module_command('t2_start','set_default_gate', 0)


    # table=3 priority=5000 in_port=3 actions=group:2953848289
    B.run_module_command('t0_inport','add', {'fields'  : [bytearray(chr(3))],
                                            'gate'     : 1})
    # otherwise drop
    B.run_module_command('t3_start','set_default_gate', 0)


    # table=4 priority=5000 ip nw_dst=10.10.12.3 actions=set_field:fa:16:3e:cf:f2:56->eth_dst output:4
    B.run_module_command('t4_start','add', {'fields'  : [bytearray(aton_ip('10.10.12.3'))],
                                            'gate'     : 1})
    # table=4 priority=5000 ip nw_dst=10.10.12.2 actions=set_field:fa:16:3e:f3:5e:82->eth_dst set_field:0x40c->tun_id set_field:1.1.1.2->tun_dst output:1
    B.run_module_command('t4_start','add', {'fields'  : [bytearray(aton_ip('10.10.12.2'))],
                                            'gate'     : 2})
    # table=4 priority=5000 ip nw_dst=10.10.10.2 actions=set_field:fa:16:3e:da:05:ed->eth_dst set_field:0x406->tun_id set_field:1.1.1.2->tun_dst output:1
    B.run_module_command('t4_start','add', {'fields'  : [bytearray(aton_ip('10.10.10.2'))],
                                            'gate'     : 3})
    # table=4 priority=5000 ip nw_dst=10.10.10.3 actions=set_field:fa:16:3e:3e:82:e8->eth_dst output:3
    B.run_module_command('t4_start','add', {'fields'  : [bytearray(aton_ip('10.10.10.3'))],
                                            'gate'     : 4})


    # table=5 priority=5000 tun_id=0x406 dl_dst=fa:16:3e:3e:82:e8 actions=output:3
    B.run_module_command('t5_start','add', {'fields'  : [bytearray(aton_tunid(0x406)),
                                                         bytearray(aton_mac('fa:16:3e:3e:82:e8'))],
                                            'gate'     : 1})
    
    # table=5 priority=5000 tun_id=0x40c dl_dst=fa:16:3e:cf:f2:56 actions=output:4
    B.run_module_command('t5_start','add', {'fields'  : [bytearray(aton_tunid(0x40c)),
                                                         bytearray(aton_mac('fa:16:3e:cf:f2:56'))],
                                            'gate'     : 2})
    # otherwise drop
    B.run_module_command('t5_start','set_default_gate', 0)


    # table=6 priority=50000 arp dl_vlan=500 actions=CONTROLLER:65535
    B.run_module_command('t6_start','add',[{'priority' : 50000,
                                            'filter'   : 'vlan 500 and arp',
                                            'gate'     : 1 }])
    # table=6 priority=5000 dl_vlan=500 actions=pop_vlan output:2
    B.run_module_command('t6_start','add', [{'priority' : 5000,
                                             'filter'   : 'vlan 500',
                                             'gate'     : 2 }])
    # otherwise drop
    # BPF automatically sets default gate to 0
